DROP FUNCTION IF EXISTS trigger_updated_at(REGCLASS) CASCADE;
DROP FUNCTION IF EXISTS set_updated_at() CASCADE;
DROP FUNCTION IF EXISTS compute_work_id(BIGINT, BIGINT, BYTEA, BYTEA) CASCADE;
DROP FUNCTION IF EXISTS utf8_txt(TEXT) CASCADE;
DROP FUNCTION IF EXISTS be64(BIGINT) CASCADE;
