//! Build script to compile BLS/Merkle wrapper contracts at build time
//!
//! Uses forge build with library linking, then reads the artifacts.

use std::path::PathBuf;
use std::process::Command;
use std::fs;

fn main() {
    println!("cargo:rerun-if-changed=contracts/BLSUtilsWrapper.sol");
    println!("cargo:rerun-if-changed=contracts/MerkleTreeWrapper.sol");
    println!("cargo:rerun-if-changed=contracts/foundry.toml");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let contracts_dir = PathBuf::from(&manifest_dir).join("contracts");
    let out_dir = std::env::var("OUT_DIR").unwrap();

    eprintln!("Compiling contracts with forge...");

    // Run forge build with library linking
    let status = Command::new("forge")
        .arg("build")
        .arg("--root")
        .arg(&contracts_dir)
        .arg("--libraries")
        .arg("urc/lib/BLSUtils.sol:BLSUtils:0x000000000000000000000000000000000000B156")
        .status()
        .expect("Failed to run forge build - is foundry installed?");

    if !status.success() {
        panic!("forge build failed");
    }

    // Read compiled artifacts
    let artifact_out_dir = contracts_dir.join("out");

    let bls_artifact = fs::read_to_string(artifact_out_dir.join("BLSUtilsWrapper.sol/BLSUtilsWrapper.json"))
        .expect("BLSUtilsWrapper.json not found");
    let bls_json: serde_json::Value = serde_json::from_str(&bls_artifact).expect("Invalid JSON");
    let bls_bytecode = bls_json["deployedBytecode"]["object"].as_str()
        .expect("No deployedBytecode.object").trim_start_matches("0x");

    let merkle_artifact = fs::read_to_string(artifact_out_dir.join("MerkleTreeWrapper.sol/MerkleTreeWrapper.json"))
        .expect("MerkleTreeWrapper.json not found");
    let merkle_json: serde_json::Value = serde_json::from_str(&merkle_artifact).expect("Invalid JSON");
    let merkle_bytecode = merkle_json["deployedBytecode"]["object"].as_str()
        .expect("No deployedBytecode.object").trim_start_matches("0x");

    let bls_utils_artifact = fs::read_to_string(artifact_out_dir.join("BLSUtils.sol/BLSUtils.json"))
        .expect("BLSUtils.json not found");
    let bls_utils_json: serde_json::Value = serde_json::from_str(&bls_utils_artifact).expect("Invalid JSON");
    let bls_utils_bytecode = bls_utils_json["deployedBytecode"]["object"].as_str()
        .expect("No deployedBytecode.object").trim_start_matches("0x");

    // Generate Rust file
    let bytecode_rs = format!(
        r#"// Generated by build.rs
pub const BLS_WRAPPER_BYTECODE: &str = "{}";
pub const MERKLE_WRAPPER_BYTECODE: &str = "{}";
pub const BLS_UTILS_LIB_BYTECODE: &str = "{}";
"#,
        bls_bytecode, merkle_bytecode, bls_utils_bytecode
    );

    let bytecode_path = PathBuf::from(&out_dir).join("compiled_contracts.rs");
    fs::write(&bytecode_path, bytecode_rs).expect("Failed to write compiled_contracts.rs");

    eprintln!("✓ Contracts compiled and bytecode extracted");
}
