//! Precompiled contract bytecode loaded at build time
//!
//! build.rs compiles contracts with library linking and generates
//! Rust constants with the bytecode.

use alloy_primitives::Bytes;
use eyre::Result;

// Include the generated bytecode constants from build.rs
mod compiled {
    include!(concat!(env!("OUT_DIR"), "/compiled_contracts.rs"));
}

/// Load precompiled BLS wrapper bytecode
pub fn load_bls_wrapper_bytecode() -> Result<Bytes> {
    let hex_str = compiled::BLS_WRAPPER_BYTECODE;
    let bytes = hex::decode(hex_str)
        .map_err(|e| eyre::eyre!("Failed to decode BLS wrapper bytecode: {}", e))?;
    Ok(Bytes::from(bytes))
}

/// Load precompiled Merkle wrapper bytecode
pub fn load_merkle_wrapper_bytecode() -> Result<Bytes> {
    let hex_str = compiled::MERKLE_WRAPPER_BYTECODE;
    let bytes = hex::decode(hex_str)
        .map_err(|e| eyre::eyre!("Failed to decode Merkle wrapper bytecode: {}", e))?;
    Ok(Bytes::from(bytes))
}

/// Load precompiled BLSUtils library bytecode
pub fn load_bls_utils_lib_bytecode() -> Result<Bytes> {
    let hex_str = compiled::BLS_UTILS_LIB_BYTECODE;
    let bytes = hex::decode(hex_str)
        .map_err(|e| eyre::eyre!("Failed to decode BLSUtils lib bytecode: {}", e))?;
    Ok(Bytes::from(bytes))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_bls_wrapper() {
        let bytecode = load_bls_wrapper_bytecode().expect("Failed to load BLS wrapper");
        assert!(!bytecode.is_empty(), "BLS wrapper bytecode should not be empty");
        assert!(bytecode.len() > 100, "Bytecode suspiciously small");
    }

    #[test]
    fn test_load_merkle_wrapper() {
        let bytecode = load_merkle_wrapper_bytecode().expect("Failed to load Merkle wrapper");
        assert!(!bytecode.is_empty(), "Merkle wrapper bytecode should not be empty");
        assert!(bytecode.len() > 100, "Bytecode suspiciously small");
    }

    #[test]
    fn test_load_bls_utils_lib() {
        let bytecode = load_bls_utils_lib_bytecode().expect("Failed to load BLSUtils lib");
        assert!(!bytecode.is_empty(), "BLSUtils lib bytecode should not be empty");
        assert!(bytecode.len() > 100, "Bytecode suspiciously small");
    }
}
